# Generated by Django 4.2 on 2023-05-17 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_licence_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_of_journey', models.DateField()),
                ('number_of_seats', models.IntegerField()),
                ('cost_per_person', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_car.car')),
                ('driver_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_car.driver')),
                ('journey_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_car.journey')),
                ('poolers', models.ManyToManyField(to='pool_car.profile')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='pool_car.profile')),
            ],
        ),
    ]
